//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{


    public partial class Default
    {

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblAppStart;

        protected global::System.Web.UI.WebControls.Label lblVisits;

        protected global::System.Web.UI.WebControls.Button btnMember;

        protected global::System.Web.UI.WebControls.Button btnStaff;

        protected global::System.Web.UI.WebControls.Button btnTestGlobal;

        protected global::System.Web.UI.WebControls.Label lblGlobalResult;

        protected global::WebApplication1.Controls.CaptchaControl MyCaptcha;

        protected global::System.Web.UI.WebControls.Button btnTestCaptcha;

        protected global::System.Web.UI.WebControls.TextBox txtEventId;

        protected global::System.Web.UI.WebControls.Button btnTestRsvp;

        protected global::System.Web.UI.WebControls.Label lblRsvpResult;

        // -----------------------------
        // Added controls (YOUR features)
        // -----------------------------

        // Cookie Demo
        protected global::System.Web.UI.WebControls.TextBox txtCookieUser;

        protected global::System.Web.UI.WebControls.TextBox txtCookieCampus;

        protected global::System.Web.UI.WebControls.Button btnSaveCookie;

        protected global::System.Web.UI.WebControls.Button btnLoadCookie;

        protected global::System.Web.UI.WebControls.Label lblCookieResult;

        // Hashing Demo
        protected global::System.Web.UI.WebControls.TextBox txtHashInput;

        protected global::System.Web.UI.WebControls.Button btnComputeHash;

        protected global::System.Web.UI.WebControls.Label lblHashResult;

        // Weather Demo
        protected global::System.Web.UI.WebControls.TextBox txtCity;

        protected global::System.Web.UI.WebControls.TextBox txtDate;

        protected global::System.Web.UI.WebControls.Button btnGetWeather;

        protected global::System.Web.UI.WebControls.Label lblWeatherResult;
    }
}
